services:
  card-service:
    build: ./
    ports:
      - "8080:8080"
    environment:
      OTEL_TRACES_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
    depends_on:
      - postgres
      - jaeger-all-in-one

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always
    ports:
      - "16686:16686"
      - "4317"
